### ISSUE TITLE
The program feedback “Connection refused”

### ISSUE THREAD

**Issue by xiaoniaoawa** [vyvir/AltLinux#21] opened 2023-11-16 12:24 UTC
I’m using Ubuntu 22.04.3LTS on my Raspberry Pi 4
I cloned the python files from this repository. Then I run it.
It repeat a log”curl:(7) Failed to connect to 127.0.0.1 port 6569 after 2 ms: Connection refused“
![image](https://github.com/i-love-altlinux/AltLinux/assets/112697401/89b616a2-3f07-4b37-903c-7a7c4eebbfd4)
![image](https://github.com/i-love-altlinux/AltLinux/assets/112697401/1b9954ae-2254-44eb-b20f-51aae6967fcd)

**Comment by NekoRectifier** [comment] 2023-12-25 16:35
In my case, the anisette server was never actually started. Because the download link that hard coded in main.py line 307 is:
```python
r = requests.get(
                "https://github.com/Dadoum/Provision/releases/download/2.1.0/anisette_server-x86_64",
                allow_redirects=True,
)
```
that link has a typo (the valid link is https://github.com/Dadoum/Provision/releases/download/2.1.0/anisette-server-x86_64)  
and that will download a "Not found" in `~/.local/share/altserver/anisette_server` which further caused the anisette server can't start and no activity on port 6969.

**Comment by LunarV2** [comment] 2024-01-20 14:01
boost

**Comment by xiaoniaoawa** [comment] 2024-01-20 14:04
what boost
________________________________
发件人: LunarV2 ***@***.***>
发送时间: Saturday, January 20, 2024 10:01:49 PM
收件人: i-love-altlinux/AltLinux ***@***.***>
抄送: xiaoniao_ ***@***.***>; Author ***@***.***>
主题: Re: [i-love-altlinux/AltLinux] The program feedback “Connection refused” (Issue #21)


boost

―

**Comment by amirisgithub** [comment] 2024-04-01 09:25
boost

**Comment by vyvir** [comment] 2024-07-19 09:16
Hi! Try the latest version of AltLinux and report if the issue still persists.

**Comment by vyvir** [comment] 2024-08-02 16:06
Duplicate of #12

**Comment by vyvir** [comment] 2024-08-02 16:11
@xiaoniaoawa please try the latest version of AltLinux and report if the issue still persists, or close the issue

**Comment by xiaoniaoawa** [comment] 2024-08-05 11:26
> @xiaoniaoawa please try the latest version of AltLinux and report if the issue still persists, or close the issue

ok! thanks, I will try, but my pi is now work on HAOS :(
I will try it later.

**Comment by xiaoniaoawa** [comment] 2024-08-06 07:52
![2024-08-06-15-51-40-435](https://github.com/user-attachments/assets/dcd3a22a-ff54-43e3-ae76-901537a5c6bb)
Hummmmmmm, it even can not install now

**Comment by xiaoniaoawa** [comment] 2024-08-06 08:01
![2024-08-06-16-00-37-761](https://github.com/user-attachments/assets/9deb45d9-593f-4eaf-b492-c9c404aac77b)
Okay, I manually installed the program, but still not work :(

**Comment by xiaoniaoawa** [comment] 2024-08-06 08:29
OHHHHHHHHHHHH
I FOUND FIX!!!

1. Clone this
2. Manually download altserver and anisette server's arm version, then put it to /your_home_dir/.local/share/altlinux/
3. Rename those two file to AltServer and anisette-server, chmod +x those two executable 
4. Go to your altlinux dir, run the py, done 👍 

Also, if your country have firewall, just replace github to kkgithub (a mirror of GitHub without firewall... in China) 

Why: the program automatic downloaded exec, but it's x86_64 version, so the program never start. We just need download and replace their exec to fix :)

**Closed** 2024-08-07 10:28 UTC
Labels: bug
